def test_main_page(main_page, maximize_window):
    main_page.open()
    main_page.start_button_is_on_page()
    main_page.start_button_opens_pop_up()
    main_page.start_with_browser()
    main_page.start_pop_up_redirection_to_sign_up()
    main_page.start_pop_up_apple_redirection()
    main_page.google_play_redirection_without_signin()
    main_page.check_menu_items()
    main_page.switch_languages()
    main_page.register_button_redirection()
    main_page.google_play_redirection()
    main_page.apple_store_redirection()
    main_page.check_toggle_switch()
